### ISSUE TITLE
Is the downloads volume used?

### ISSUE THREAD

**Issue by briandipalma** [linuxserver/docker-jackett#103]
Not a bug per se but I don't see what the volume config

```
-v <path to blackhole>:/downloads
```

is used for, I see no reference to it in the Dockerfile. Is this something left over from an earlier version? Happy to raise a PR to remove it from the README if so.

**Comment by tobbenb** [comment]
We removed it from the dockerfile in case people don't want to use /downloads as the path. If it's defined in the dockerfile and not used as a volume bind, a volume is made without the user knowing it.

The /downloads bind mount is for downloads.

**Comment by briandipalma** [comment]
OK so this is for some sort of manual torrent download feature that Jackett supports I'm guessing? So I should probably set it to the Transmission watch directory so that I get semi-automatic downloads?

**Comment by tobbenb** [comment]
I thought jackett was a torrent downloader, but reading the readme it's not. So not sure what the /downloads folder is for.

**Comment by briandipalma** [comment]
OK so it seems we're both confused. It's not important but it would be good to clarify what exactly it's for and if it's not required it I can remove it from the docs.

**Comment by tobbenb** [comment]
It's to pass the torrent file to the torrent client.

**Comment by TrikkStar** [comment]
> It's to pass the torrent file to the torrent client.

Could you perhaps update this accordingly in the parameter description? As right now it still says "Path to torrent blackhole." which is pretty vague, also would be nice if it was appropriately marked as optional.
