### ISSUE TITLE
Execute permission on /app/Jackett/jackett disappears after update

### ISSUE THREAD

**Issue by vecnar** [linuxserver/docker-jackett#104]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
After update it should work as normal

## Current Behavior
Jackett fails to start after update with below errors in the log
"/app/Jackett/jackett_launcher.sh: 10: /app/Jackett/jackett_launcher.sh: /app/Jackett/jackett: Permission denied"

## Steps to Reproduce
1. Download the docker "linuxserver/jackett:arm64v8-latest"
2. Login to web ui and press on "check for updates" button
3. After it finds update v0.16.1077, downloads it, runs install, restarts and fails to start
4. Connecting to docker cli, giving execute permission to /app/Jackett/jackett and restarting docker resolves problem until next update, at least it happened with old docker image i had before update.

## Environment
**OS:** Debian GNU/Linux 9     
**CPU architecture:**arm64      
**How docker service was installed:** From terminal using below command
"docker run -itd --name=jackett --net=container:Openvpn \
-v /sharedfolders/Appdata/jackett:/config \
-v /sharedfolders/Temp/Downloads/WatchFolder:/downloads \
-e PGID=1001 -e PUID=1006 \
-e TZ=Europe/Dublin \
--restart=unless-stopped \
linuxserver/jackett:arm64v8-latest
"     

## Docker logs
I have recreated the docker and reproduced the error, it seems to be the problem with update v0.16.1077

[DockerLogs.txt](https://github.com/linuxserver/docker-jackett/files/5180598/DockerLogs.txt)

Let me know if you need more information.

Thank you

**Comment by aptalca** [comment]
We don't recommend or support updating via web gui inside the container. Supported updating instructions are in the readme.
