### ISSUE TITLE
 Option 'ProxyConnection' is unknown.

### ISSUE THREAD

**Issue by Anzic23** [linuxserver/docker-jackett#111]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Start with a configured proxy.
## Current Behavior
error to start container

## Steps to Reproduce
     environment:
      - RUN_OPTS=--ProxyConnection=172.23.0.57:8118

## Environment
**OS:** synology
**CPU architecture:** arm64
**How docker service was installed:**
from the official docker repo

## Command used to create docker container (run/create/compose/screenshot)
  jackett:
    image: linuxserver/jackett
    networks:
      default:
        ipv4_address: 172.23.0.54
    container_name: jackett
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Moscow
      - RUN_OPTS=--ProxyConnection=172.23.0.57:8118
    volumes:
      - ./jackett/config:/config
      - ./downloadclient-downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
## Docker logs
```
    
  Option 'ProxyConnection' is unknown.




  -i, --Install            Install Jackett windows service (Must be admin)




  -r, --ReserveUrls        (Re)Register windows port reservations (Required for


                           listening on all interfaces).




  -u, --Uninstall          Uninstall Jackett windows service (Must be admin).




  -l, --Logging            Log all requests/responses to Jackett




  -t, --Tracing            Enable tracing




  -c, --UseClient          Override web client selection.


                           [automatic(Default)/httpclient/httpclient2]




  -s, --Start              Start the Jacket Windows service (Must be admin)




  -k, --Stop               Stop the Jacket Windows service (Must be admin)




  -x, --ListenPublic       Listen publicly




  -z, --ListenPrivate      Only allow local access




  -p, --Port               Web server port




  -m, --MigrateSettings    Migrate settings manually (Must be admin on Windows)




  -n, --IgnoreSslErrors    [true/false] Ignores invalid SSL certificates




  -d, --DataFolder         Specify the location of the data folder (Must be


                           admin on Windows) eg. --DataFolder="D:\Your


                           Data\Jackett\". Don't use this on Unix (mono)


                           systems. On Unix just adjust the HOME directory of


                           the user to the datadir or set the XDG_CONFIG_HOME


                           environment variable.




  --NoRestart              Don't restart after update




  --PIDFile                Specify the location of PID file




  --NoUpdates              Disable automatic updates




  --help                   Display this help screen.




  --version                Display version information.






Jackett v0.17.159
```

**Comment by aptalca** [comment]
I'm confused. Are you making a statement or asking a question?

The error is self explanatory. Jackett doesn't understand the option you're trying to pass.

What exactly is the purpose of this ticket?

**Comment by RoelSG** [comment]
Had the same behaviour:

Using the - RUN_OPTS=--ProxyConnection=proxyip 

This option is directly mentioned in the parameter documentation. I removed the RUN_OPTS variable and the container started normally. I think something changed in upstream Jackett.

**Comment by Roxedus** [comment]
Yes. https://github.com/Jackett/Jackett/commit/edce56f36311767f9bff3f1944ea1f0d929ab0e0

**Comment by RoelSG** [comment]
Very clear-cut. I think only a documentation change is needed, but apparently the option also did nothing before.

**Comment by Roxedus** [comment]
Correct
