### ISSUE TITLE
Location of Definitions 

### ISSUE THREAD

**Issue by joells101** [linuxserver/docker-jackett#115]
i've encountered the linked issue below
https://www.reddit.com/r/radarr/comments/kbs5sh/manual_search_in_v3_a_little_broken/

there is a link to another issue on github about customer definitions
https://github.com/linuxserver/docker-jackett/issues/72#issuecomment-468859532

basically i'm looking for one of the following /config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Jackett/Definitions

there is nothing in the mapped /config for definitions and the other local locations are empty too for obvious reasons. apparently i need to modify 

this 
modes:
    search: [q, imdbid]
    movie-search: [q, imdbid]

to 
modes:
    search: [q]
    movie-search: [q]

but from what i can see the docker image doesnt seem to have that index file anywhere?

**Comment by slikie** [comment]
Yes the definition file won't be there but you can grab a copy and rename its name and id, put it in config/cardigann/definitions/ and use it as a different indexer
