### ISSUE TITLE
OpenVPN Support with Container Killswitch

### ISSUE THREAD

**Issue by drewwats** [linuxserver/docker-jackett#116]
I am interested in masking the requests going out to torrent/nzb sites via OpenVPN. 

------------------------------

## Desired Behavior
Similar to haugene/transmission-openvpn, container will not run if VPN is not successfully connected. 

## Current Behavior
Requests are sent without any obfuscation of IP address. 

## Alternatives Considered
Running VPN at a higher level is not feasible.

**Comment by tobbenb** [comment]
This is something we will not support.

**Comment by drewwats** [comment]
Wow, an impressively quick decline.

**Comment by Roxedus** [comment]
This gets brought up from time to time. It would create a support nightmare, which is not something we want to have. Nothing is stopping you form spinning up a openvpn client container, and route the traffic trough it.

**Comment by aptalca** [comment]
@drewwats 
You are welcome to ask for help in the #other-support channel of our discord.

Plenty of people accomplish that by routing the connection through our wireguard container.

**Comment by drewwats** [comment]
Thank you for the info and suggesting an alternative. It appears I should be able to use the transmission-openvpn container to create a proxy to pass Jackett through. That should be good enough.
