### ISSUE TITLE
Update image because of new jackett commit

### ISSUE THREAD

**Issue by albatr0ss** [linuxserver/docker-jackett#117]
Jackett was not returning results when used with Sonarr. 
Jackett made a new commit to resolve the issue by removing the keywordfilters section.
[https://github.com/Jackett/Jackett/issues/11471](url)

Please update the container to get docker version working with sonarr.

**Comment by Roxedus** [comment]
You are barking up the wrong tree. The last commit in the linked issue has not made it to a Jackett release, so we have nothing to update to.

**Comment by albatr0ss** [comment]
First: I was not barking but trying to be collaborative
Second: Jackett was updated 3 hours ago.
![jackett](https://user-images.githubusercontent.com/39968575/120631847-9cb9d780-c468-11eb-96c9-0d6c10a12bfc.png)

**Comment by Roxedus** [comment]
And no new release has been made after that commit. https://github.com/Jackett/Jackett/releases 

We depend on Jackett to create releases to provide updates.

**Comment by albatr0ss** [comment]
Thank you for your explanation Roxedus.
Is there a way to do a manual pull (or any other way to update jackett) from within the container?
