### ISSUE TITLE
Docker tags are incorrect

### ISSUE THREAD

**Issue by ngosang** [linuxserver/docker-jackett#118]
In this image => ghcr.io/linuxserver/jackett:0.18.891

I expect to see the content of the `master` branch. If you take a look inside the image you can see the file `/etc/services.d/jackett/run` was taken from `development` branch instead of `master`.

This is an issue because the environment variable `AUTO_UPDATE=true` is not working in development branch.

**Update. The first tag is misleading.**
0.18.891 => development
version-v0.18.891 => master

**Comment by thelamer** [comment]
Our tagging gets wonky for repos that share releases for dev/staging and production. 
We have a root tag that should be unique and never collide (comprised of package hash, branch if not master, external version, and our internal incrementing integer) but for the shortened ones like version and such that were implemented later you can potentially have scenarios where an image is overwritten so a user running v1.0.0 could pull two different images at different times depending on when and how the releases were cut if the upstream external tag collides. 
I don't think we have a solution to this short of forcing the branch name along with the external version, which was rejected internally when implementing these simplified version tags.
