### ISSUE TITLE
unable to change torrentleech URL to torrentleech.me

### ISSUE THREAD

**Issue by chenks** [linuxserver/docker-jackett#125]
my ISP has now blocked torrentleech.cc but torrentleech.me still works.
attempting to change the URL in jackett fails saying

```
 An error occurred while updating this indexer
The SSL connection could not be established, see inner exception.: Cannot determine the frame size or a corrupted frame was received.
```

i can browse torrentleech.me fine in a web browser so no idea why jackett is having issues.

**Comment by chenks** [comment]
[log.txt](https://github.com/linuxserver/docker-jackett/files/9109454/log.txt)
log attached

**Comment by Roxedus** [comment]
Not a container issue.

**Comment by chenks** [comment]
why is not a container issue?
i would suggest it is, as i have no issues with the URL anywhere other than within the container.

**Comment by Roxedus** [comment]
The issue is with the application or your networking.

**Comment by Roxedus** [comment]
This is not the repository of jackett, just a container image packaging the application.
