### ISSUE TITLE
I have the fork Jackett-public working in my fork of this repo. Interest?

### ISSUE THREAD

**Issue by Electronickss** [linuxserver/docker-jackett#13]
I made some tweaks to the Dockerfile to use the [public fork of Jackett](https://github.com/dreamcat4/Jackett-public). Would there be interest in creating a PR or taking over the repo to produce autobuilds from there?

**Comment by lonix** [comment]
I Bet submitting a PR would be the best option.

**Comment by sparklyballs** [comment]
I'm gonna close this as it not an issue per se, the public "version" looks to be a fork from the last version of Jackett that supported public trackers and there doesn't seem to me to have been much development since then.

**Comment by Electronickss** [comment]
Correct. Unfortunately after I got it working I realized it was broken. I apologize for making a ruckus over a broken project. Its unfortunate that the current version of jackett no longer supports public trackers
