### ISSUE TITLE
Random container shutdowns

### ISSUE THREAD

**Issue by truthsword** [linuxserver/docker-jackett#138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

jackett container stops often (without restarting). Here's what the log offers:
Unclear why this is occurring.

Logs attached
[_jackett_logs.txt](https://github.com/linuxserver/docker-jackett/files/10737390/_jackett_logs.txt)

### Expected Behavior

jackett container runs with=out interruption, or restarts automatically.

### Steps To Reproduce

Launch with docker-compose
Check container status after a few days

### Environment

```markdown
- OS: Debian 11
- How docker service was installed: Standard
```

### CPU architecture

x86-64

### Docker creation

```bash
docker-compose:

version: "3"
services:
  linuxserver-jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PGID=1001
      - PUID=1001
      - TZ=America/New_York
      - AUTO_UPDATE=true
    volumes:
      - /home/user/docker/jackett/downloads:/downloads
      - /home/user/docker/jackett:/config
    restart: unless-stopped
    network_mode: "container:gluetun"
```
```


### Container logs

```bash
Container log attached above
```

**Comment by j0nnymoe** [comment]
It's going to be your gluetun connection dropping/reconnecting.

**Comment by truthsword** [comment]
How would I have the jackett container restart when that happens? Would combining the compose files help? Thank you.

Feb 14, 2023 5:24:43 PM j0nnymoe ***@***.***>:

**Comment by j0nnymoe** [comment]
It's outside of our support. You'd need to have something monitoring the port to then jackett restart when it becomes unavailable.
