### ISSUE TITLE
Container restarting loop

### ISSUE THREAD

**Issue by laurentbinagot** [linuxserver/docker-jackett#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I run my container he is restarting again and again 

### Expected Behavior

see the previous test I tried on this issue https://github.com/Jackett/Jackett/issues/14858

### Steps To Reproduce

docker-compose pull
docker-compose up -d
and then container starting, ip_addresse was attributed and lost and restarting again and again

### Environment

```markdown
- OS:Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "3"
services:
jackett:
image: ghcr.io/linuxserver/jackett:arm64v8-latest
container_name: jackett
environment:
- TZ=Europe/Paris
- AUTO_UPDATE=true
- PUID=1000
- PGID=1000
volumes:
- ./config:/config
#- ./jackett/blackhole:/downloads
ports:
- 9117:9117
restart: unless-stopped
networks:
- cloudflare
depends_on:
- flaresolverr
flaresolverr:
image: ghcr.io/flaresolverr/flaresolverr
container_name: flaresolverr
environment:
- LOG_LEVEL=info
#- CAPTCHA_SOLVER=hcaptcha-solver
- LANG=en_US
ports:
- 8191:8191
restart: unless-stopped
networks:
- cloudflare

networks:
cloudflare:
external: false
enable_ipv6: false
```

### Container logs

```bash
no logs due to not starting completely
```

**Comment by j0nnymoe** [comment]
We need to see the container start up logs, you can get these by doing `docker logs jackett`.

**Comment by laurentbinagot** [comment]
there is no logs even with the command `docker logs jackett`

**Comment by thespad** [comment]
I suspect your issue is due to this https://github.com/raspberrypi/linux/issues/5402

See https://www.linuxserver.io/armhf for more context.

**Comment by laurentbinagot** [comment]
So I have to reinstall entirely my Pi with a 64bit OS ?
I was convince that was already my case but apparently not :/

**Comment by thespad** [comment]
If you followed the default Raspbian install you will have got a 32-bit OS, and then they're upgrading your kernel to 64-bit giving you a mixed kernel/userspace that causes all kinds of odd issues.

If you choose to use Raspbian again (and I wouldn't), make sure you definitely get the 64-bit install as they're still pushing 32-bit as the default download.

**Comment by laurentbinagot** [comment]
ok thanks, what OS do you recommend me ? I want a small one

**Comment by thespad** [comment]
There are plenty of options, but for a headless SBC install we would typically recommend something like [Ubuntu](https://ubuntu.com/tutorials/how-to-install-ubuntu-on-your-raspberry-pi) or [DietPi](https://dietpi.com/docs/install/). Which you should pick is down to your specific requirements.

**Comment by laurentbinagot** [comment]
For now it’s too complicated to reinstall a newer 64OS so I’ll try install on my NAS and if it work I’ll see later

**Comment by laurentbinagot** [comment]
I finally reinstalled with Ubuntu 64 bits and It work

thanks for the help
