### ISSUE TITLE
 FlareSolverr API URL

### ISSUE THREAD

**Issue by Bl00d-B0b** [linuxserver/docker-jackett#146]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

As I can see, now  FlareSolverr is a part of the jackett build.
/app/Jackett/FlareSolverrSharp.dll
but I can't find, on which port is runned, and how It can be used.

### Reason for change

Some torrents protected by Cloudflare, I I can't find which port I need to use to setup FlareSolverr API URL

**Comment by j0nnymoe** [comment]
Their documentation still shows you need to set it up separately https://github.com/Jackett/Jackett#configuring-flaresolverr

**Comment by Bl00d-B0b** [comment]
I read docs, and it's written: [FlareSolverr](https://github.com/FlareSolverr/FlareSolverr) has been integrated into Jackett. This service is in charge of solving the challenges and configuring Jackett with the necessary cookies. 
to setup:
1) Install FlareSolverr service (following their instructions) --- my assumption it's is already installed in this linuxserver/jackett, as I can see 
/app/Jackett/FlareSolverrSharp.dll
2) Configure FlareSolverr API URL in Jackett. For example: http://172.17.0.2:8191/ --- that's my question, if it's already installd, what URL i must setup in the setting?

![image](https://github.com/linuxserver/docker-jackett/assets/23188529/8e554f62-1e52-4f0f-85df-55f8f505e6b8)

So, my assumption, this service is not run inside this jackett build.

**Comment by Bl00d-B0b** [comment]
OK, thanks.
