### ISSUE TITLE
[FEAT] Add FlareSolverr 

### ISSUE THREAD

**Issue by Poopselon** [linuxserver/docker-jackett#147]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Install FlareSolverr package into container.

### Reason for change

1337x torrents started using clouflare challenge and jacket can't index. 
Error:
 An error occurred while testing this indexer
Exception (1337x): Challenge detected but FlareSolverr is not configured: Challenge detected but FlareSolverr is not configured

### Proposed code change

Changes documented in jacket documentation. https://github.com/Jackett/Jackett#configuring-flaresolverr

**Comment by Roxedus** [comment]
You can use the flaresolverr container and integrate it like intended.

**Comment by Poopselon** [comment]
But why not integrate it in same container?

**Comment by Roxedus** [comment]
It does not belong in the same container. Its not a requirement for jackett to work.

**Comment by Poopselon** [comment]
Ok, thanks
