### ISSUE TITLE
[BUG] Can't run via docker-compose on mac m1

### ISSUE THREAD

**Issue by cringelord1940** [linuxserver/docker-jackett#153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error response from daemon: Mounts denied:
The path /path/to/blackhole is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/desktop/mac for more info.

### Steps To Reproduce

1. run the compose.yml here https://hub.docker.com/r/linuxserver/jackett/
2. simply can't mount the container

### Environment

```markdown
- OS:macos 14.1.2
- How docker service was installed: via Homebrew-Cask
```

### CPU architecture

arm64

### Docker creation

```bash
---
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /path/to/jackett/data:/config
      - /path/to/blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
```

### Container logs

```bash
can't mount to log
```

**Comment by thespad** [comment]
`/path/to/jackett/data` and `/path/to/blackhole` are placeholders, you're supposed to use an actual path that exists on your host and where you want to store the corresponding data.
