### ISSUE TITLE
[BUG] External Trigger Main action failing

### ISSUE THREAD

**Issue by ilike2burnthing** [linuxserver/docker-jackett#157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Action failing since last week with error `jq: error (at <stdin>:1): Cannot iterate over null (null)` - https://github.com/linuxserver/docker-jackett/actions/runs/12114744301/job/33771798996

Appears to be affecting other repos on and off as well:
- https://github.com/linuxserver/docker-htpcmanager/actions/runs/12266524631/job/34224825573
- https://github.com/linuxserver/docker-ubooquity/actions/runs/12265958128/job/34223118054
- https://github.com/linuxserver/docker-kasm/actions/runs/12265143429/job/34220553516
- https://github.com/linuxserver/docker-bazarr/actions/runs/12264210424/job/34217559026

Possibly because accessing https://ci.linuxserver.io/ often (mostly?) times out.

**Comment by aptalca** [comment]
This is already fixed in jenkins builder and will waterfall during package check build over the next few days
