### ISSUE TITLE
Docker version 44 downloads old version of Jackett ( 0.7.1006.0 )

### ISSUE THREAD

**Issue by muhahacz** [linuxserver/docker-jackett#19]
Jackett docker file version (Linuxserver.io version:- 44 Build-date:- February-10-2017-23:48:27-UTC) downloads old version of Jackett ( 0.7.1006.0 )

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Ubuntu 16.04.2 LTS

sudo docker run  --restart=always --name=jackett -v /docker/jackett/config:/config -v /docker/jackett/downloads:/downloads -e TZ=Europe/Prague -p 9117:9117 linuxserver/jackett

http://pastebin.com/VYjfg3FB

image hash:
sha256:e588088688699b02eeac469d8982a927981f4e1459f8c3661e97018db7edd82e

**Comment by sparklyballs** [comment]
it uses the version that was current at the time the image was built.
the next weekly update tomorrow will use whatever version is current then.

this is normal behaviour for the image, closing this.
