### ISSUE TITLE
Jackett Crashes after a couple of days

### ISSUE THREAD

**Issue by JoeStratton** [linuxserver/docker-jackett#22]
I am not sure what to provide here as the docker logs arnt showing any errors, but every few days my sonarr/radarr installation tells me my jackett-based indexers arnt working. When I go look at jackett's UI everything seems ok except the "test" function just sits endlessly. 

Once I restart the jackett container everything works again normally. Is this a known issue? Is there anything I can provide to help? Thanks!
	

 unRAID 6.3.2 

![jackett](https://cloud.githubusercontent.com/assets/6180439/25090218/d93fb40e-2336-11e7-99d2-df13076aa2c0.PNG)

**Comment by sparklyballs** [comment]
try disabling autoupdates in the webui

**Comment by JoeStratton** [comment]
Thanks, completely missed that option. Ill let it sit for a few days and see what happens.
