### ISSUE TITLE
Save Jackett settings in container

### ISSUE THREAD

**Issue by faustusdotbe** [linuxserver/docker-jackett#25]
Hi, perhaps more of a question than an issue, perhaps more related to me being unfamiliar with Docker, too.

How does one retain the Jackett settings? Whenever I stop and restart the container (in my Synology), the Jackett config is gone. I can't find this information anywhere in the README nor documentation.

Thanks!

**Comment by brandborg** [comment]
Please don't try to save the settings inside the container. Instead mount a volume from your container to your host machines hard drive. - This can either be done by mounting a folder or by mounting a file directly.
More information can be found here:
https://docs.docker.com/engine/tutorials/dockervolumes/

**Comment by faustusdotbe** [comment]
I'll do that, thank you.
