### ISSUE TITLE
Test failed for isohunt: An error occurred while sending the request: Error: TrustFailure (Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED at /tmp/buildd/mono-5.0.1.1/external/boringssl/ssl/handshake_client.c:1132)

### ISSUE THREAD

**Issue by jbmorgado** [linuxserver/docker-jackett#26]
Docker container under Arch Linux

Created with: `sudo docker create --name=jackett -v /home/docker/jackett/config:/config -v /home/docker/jackett/downloads:/downloads -e PGID=617 -e PUID=617 -e TZ=Europe/Lisbon -p 9117:9117 --restart=unless-stopped linuxserver/jackett`

Can't connect to the majority of trackers with a similar message.

**Comment by romainvv** [comment]
I have a similar issue with mono 5.0.1.1 on ubuntu without docker.

**Comment by jserdaru** [comment]
Same problem with this last version of the docker image. Almost all trackers fail with that message.

**Comment by Philiphlop** [comment]
I had a very similar issue earlier today, but having restarted the server/container it is now working again. Another search suggested not having SSL certs synced, but that was for non-container release. Have you tried restarting the container? 

```
docker restart jackett
```

Or recreating it?

```
docker rm -f jackett
Then re-use your docker create/run command
```

As all config is stored externally you wouldn't lose anything. This should force a rebuild and therefore re-sync of the SSL certs.

**Comment by jserdaru** [comment]
Restarting fixed the problem. Thanks.

**Comment by ZataH** [comment]
I have same error on a few trackers. Tried to restart container. Delete/re-create container. Still same issue

**Comment by sparklyballs** [comment]
closing this as original problem seems to have been resolved
