### ISSUE TITLE
Massive log file size.

### ISSUE THREAD

**Issue by supremacy2k** [linuxserver/docker-jackett#28]
Jackett eats a good amount of space in log files.
Is it possible to add logrotate to jackett log files within the container?

**Comment by haydenknowles** [comment]
Yup same problem here

**Comment by FedoraTipper** [comment]
Also same problem here.

**Comment by wcomartin** [comment]
Any solution to this yet?

**Comment by thelamer** [comment]
@supremacy2k @haydenknowles @FedoraTipper @wcomartin 

You have to understand at the core of Docker which is running one application inside of a container. What you are all talking about would be to add logrotate to this image and have it run as a seperate daemon. 

From a docker perspective you can set a max size for logs (the stdout information) using the following syntax: 
```
--log-opt max-size=10m --log-opt max-file=3
```
As for Jackett logs the developers really should bake that into their application or provide an option to disable them. I highly recommend getting in contact with them here to get that feature implemented. At the very least being able to disable logs should not be a big change considering they already have a debugging flag for logs in the WebUI. 

https://github.com/Jackett/Jackett/issues

**Comment by RyanAStrouse** [comment]
Same here!

**Comment by kaso17** [comment]
@thelamer jackett has log rotate build in (3M max).
I would suggest to add the docker log options to the readme.
