### ISSUE TITLE
Update to v0.7.1557

### ISSUE THREAD

**Issue by hugolapointe** [linuxserver/docker-jackett#29]
It will be useful if you upgrade the jackett version to at least the version v0.7.1557. Several trackers have change since.

Thanks you.

**Comment by sparklyballs** [comment]
image is rebuilt every friday to whatever the latest release is at that time.

it will be rebuilt in a few hours time.

**Comment by hugolapointe** [comment]
Even if the version is a pre-release?

**Comment by sparklyballs** [comment]
no, if it is a release.

we don't support pre-releases

**Comment by hugolapointe** [comment]
Is it a way for me to update the container to the pre-release?
