### ISSUE TITLE
Allow to install pre-build version of Jackett

### ISSUE THREAD

**Issue by welcoMattic** [linuxserver/docker-jackett#30]
Is it possible to let us install pre-build version of Jackett to get lastest trackers?

Thanks

**Comment by alphayax** [comment]
I've tried... And it does not work :'(
It's a shame cause I really need the t411v2 provider.

**Comment by alphayax** [comment]
But you can solve your problem by editing the dockerfile and build from the last prerelease id.

**Comment by welcoMattic** [comment]
@alphayax Yup, but I use it in a docker-compose stack. I'll update Dockerfile, and submit a PR later ;)

**Comment by sparklyballs** [comment]
![screen shot 2017-08-28 at 21 30 56](https://user-images.githubusercontent.com/4343808/29888155-cbe231e2-8db7-11e7-905e-97fb855564a4.png)


question was asked this week in the discord channel for jackett and the dev advises to not use pre-release to build our docker from
