### ISSUE TITLE
Latest Jackett update kills this container (not pre-release)

### ISSUE THREAD

**Issue by M1ntBerryCrunch** [linuxserver/docker-jackett#33]
This official release is failing the same way the pre-release was. How do I get this running on the latest (not-pre) release? 
Thanks

**Comment by sparklyballs** [comment]
`This official release is failing the same way the pre-release was.`

how was the pre-release failing ? how and why did you install the prelease ? 

we need more information than you're currently supplying here.

**Comment by M1ntBerryCrunch** [comment]
I had been trying to update to the pre-release because several trackers were failing to work properly. Once I update from "Jackett Version 0.7.1644.0" to the 0.8 version the trackers no longer show, the Jackett Version is blank and the "view logs" and "check for updates" buttons don't work.

**Comment by M1ntBerryCrunch** [comment]
Sorry to double post. I'm using the "check for updates" button, which has worked before. Did this container update to v0.8.128 for anyone? Maybe I just need to make notes of my trackers and settings and start over?  :(

**Comment by M1ntBerryCrunch** [comment]
Is it possible that the folder structure has changed in Jackett? Maybe once updated it is looking for  "ServerConfig.json", and the "Indexers" folder in the wrong location inside the container?
Part of why I think that is because the web address changes from "/Admin/Dashboard" to "/UI/Dashboard" in this update.

If this is totally my issue, I'm sorry. 
Thanks

**Comment by M1ntBerryCrunch** [comment]
Okay, I entered the container and made "/var/services" folder with 777 permission to test and the update worked.

pls see this: https://github.com/Jackett/Jackett/issues/1760

**Comment by j0nnymoe** [comment]
@M1ntBerryCrunch I would suggest updating the container rather than the application within the container. All our images get rebuilt on a Friday 11pm GMT so that we catch any application/dependency updates.
