### ISSUE TITLE
Notice: "Jackett is running with root privileges"

### ISSUE THREAD

**Issue by llaumgui** [linuxserver/docker-jackett#35]
Hi,

since [this Jackett's commit](https://github.com/Jackett/Jackett/commit/05d57980465265fa42c349df1c5b1acf28000ba0), the docker container add notice:
> Jackett is running with root privileges. You should run Jackett as an unprivileged user.

Is't possible to pass by a jackett user ?

**Comment by aptalca** [comment]
Set the PUID and PGID variables to a non-root user as described in the readme

**Comment by tudor131313** [comment]
How would we go about that in ubuntu? can anyone post the commands for someone like me, who is a complete noob when it comes to this? 

Thank you in advance!

**Comment by mickremy** [comment]
I have the same issue on my Synology. I created a specific user and user group for my docker containers and still I have the message "Jackett is running with root privileges". I don't get why or wwhat I should change.

**Comment by hapylestat** [comment]
It makes no sense at all.   I'm using podman and have configured group and user mapping, where root in container is not a real root in a base system (rootless containers). 

And this message making totally no sense for me!

**Comment by aptalca** [comment]
Post your compose yaml or docker run
