### ISSUE TITLE
docker-jackett chowns mounted directories/volumes unnecessarily?

### ISSUE THREAD

**Issue by n1nj4888** [linuxserver/docker-jackett#37]
docker-jackett seems to unnecessarily “chown” mounted directories to the docker-jackett container PUID?

For example, when the docker-jackett container is started, it changes the owner of say directory X (a mounted directory in the container) to the PUID of the docker-jackett container, yet this same directory maybe also used by other docker containers (say docker-container-B) as well... this results in a strange situation where, if docker-container-B starts after the docker-jackett container and then writes to the same directory, all files are owned in the directory by docker-jackett PUID?

Using Synology Docker...

**Comment by tobbenb** [comment]
Can't you use the same UID on both containers?

**Comment by n1nj4888** [comment]
I could but that’s not exactly solving the problem. I’d rather run each container with its own UID to better control which container can do what.

**Comment by n1nj4888** [comment]
Perhaps a better way would be to have an environment variable called DONT_CHANGE_DIR_OWNERSHIP or similar such that, when changed to true, it does not chown any of the configured mounted directories accept /config ?

**Comment by sparklyballs** [comment]
> I could but that’s not exactly solving the problem

your setup having separate PxID for each container is creating the problem
