### ISSUE TITLE
Libcurl failed to initialize

### ISSUE THREAD

**Issue by deevus** [linuxserver/docker-jackett#38]
I've been using Jackett without issue for a long time, but recently it has stopped working after I updated the image. 

Host OS: Synology DSM 6
Created using DSM docker manager

```
12-12 11:29:52 Info Adding aggregate indexer 
12-12 11:29:52 Warn Libcurl failed to initalize. Did you install it? 
12-12 11:29:52 Warn Debian: apt-get install libcurl4-openssl-dev 
12-12 11:29:52 Error Top level exception System.DllNotFoundException: libcurl
  at Jackett.Utils.Clients.UnixLibCurlWebClient.Init () [0x0008a] in <0f6344813a0d49efa2c0dd536a9ad71a>:0 
  at Jackett.Services.ServerService.Initalize () [0x003e0] in <0f6344813a0d49efa2c0dd536a9ad71a>:0 
  at JackettConsole.Program.Main (System.String[] args) [0x0058a] in <57581ca9af78422ab46352f25efa2bc3>:0 
```

I was able to resolve by executing `apk add curl-dev` inside the running container.

**Comment by sparklyballs** [comment]
are you using our image here ?

`12-12 09:35:18 Info Adding aggregate indexer
12-12 09:35:18 Info Starting web server at http://*:9117/`

with a fresh pull and also our jackett image is ubuntu based so apk would not work

**Comment by deevus** [comment]
Hmm it's definitely a linuxserver image. I'll make sure to do a fresh pull. Probably something on my end then.

**Comment by sparklyballs** [comment]
you definitely don't have the latest image because this was moved away from alpine in april 2017
