### ISSUE TITLE
ServerConfig.json gets overwritten every time docker image is updated

### ISSUE THREAD

**Issue by zgmfx** [linuxserver/docker-jackett#41]
Recently whenever I pull the latest version of this docker image and restart it, my ServerConfig.json file is getting overwritten with a seemingly default one.  I'm losing my specific settings such as the APIKey and BasePathOverride that are preventing other containers from accessing this one.

My ServerConfig.json is stored on my Host's drive that I'm mapping  to /config of this container. 

I just noticed this happening in the last few weeks or so.  Previously whenever this docker image got updated my config was untouched.

**Comment by j0nnymoe** [comment]
Is this still an issue? please could you post some more information about your setup - host os/docker command? Thanks

**Comment by zgmfx** [comment]
I haven't tried updating the docker image since I logged the issue.  But I just tried pulling the latest and restarting the container and I did not have the issue this time.

**Comment by sparklyballs** [comment]
in that case closing this
