### ISSUE TITLE
unable to pull your image

### ISSUE THREAD

**Issue by jodumont** [linuxserver/docker-jackett#42]
when I try `docker pull linuxserver/jackett`
it result an error

> docker pull linuxserver/jackett
> Using default tag: latest
> latest: Pulling from linuxserver/jackett
> 4e2e76526c94: Already exists
> 9b420d767d74: Already exists
> 71becf26860f: Already exists
> a3b46a5e0012: Already exists
> 703787483247: Already exists
> 4431a105bf56: Already exists
> 3e57e8ce0540: Already exists
> 140b510e4841: Already exists
> 00e44ad23245: Already exists
> 1aa29ca7bbe5: Extracting  4.524MB/4.524MB
> 09ccdb48553d: Download complete
> failed to register layer: ApplyLayer exit status 1 stdout:  stderr: Container ID 197121 cannot be mapped to a host ID

I run a bunch of image from linuxserver and others without any issue

the error is not present if I pull : `linuxserver/jackett:90`

**Comment by arnishow** [comment]
same thing here

**Comment by nichols-356** [comment]
ran into this when I noticed my image wasn't updating. had to specify linuxserver/jackett:166 as the image and it grabbed the latest.

**Comment by arnishow** [comment]
Any news of this? Still blocked with version 90. Thanks

**Comment by j0nnymoe** [comment]
Example of your docker run command please

**Comment by arnishow** [comment]
`root@jupiter:/docker pull linuxserver/jackett:latest`
`Using default tag: latest`
`latest: Pulling from linuxserver/jackett`
`04651435ae61: Already exists`
`36ddf2675bcc: Already exists`
`6fde24da9094: Already exists`
`b21f90624997: Already exists`
`cf301f1c7552: Already exists`
`274a2284e795: Already exists`
`af4655af427d: Already exists`
`2c4d80c984fa: Already exists`
`e8ccdada35ea: Already exists`
`eacf102f2deb: Extracting  4.818MB/4.818MB`
`72724bec4b90: Download complete`
`failed to register layer: ApplyLayer exit status 1 stdout:  stderr: Container ID 197121 cannot be mapped to a host ID`

**Log:**
`Jun 11 23:02:49 jupiter dockerd[4937]: time="2018-06-11T23:02:49.244095100+02:00" level=info msg="Attempting next endpoint for pull after error: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: Container ID 197121 cannot be mapped to a host ID"`

**Comment by j0nnymoe** [comment]
Ok so host os?

**Comment by arnishow** [comment]
root@jupiter:/docker uname  -a
Linux jupiter 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GN                                                                                        U/Linux


root@jupiter:/docker docker info
Containers: 14
 Running: 14
 Paused: 0
 Stopped: 0
Images: 14
Server Version: 18.03.1-ce
Storage Driver: btrfs
 Build Version: Btrfs v4.7.3
 Library Version: 101
Logging Driver: syslog
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: xx
runc version: xx
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
 userns
Kernel Version: 4.9.0-6-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.67GiB
Name: jupiter
ID: xxx
Docker Root Dir: /docker/200000.200000
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true

For information it's perfectly working with linuxserver/transmission, linuxserver/radarr, linuxserver/medusa, etc.

**Comment by j0nnymoe** [comment]
@arnishow just tried this myself on a test VM:
```[root@VM j0nnymoe]# docker pull linuxserver/jackett
Using default tag: latest
latest: Pulling from linuxserver/jackett
04651435ae61: Pull complete 
36ddf2675bcc: Pull complete 
6fde24da9094: Pull complete 
b21f90624997: Pull complete 
cf301f1c7552: Pull complete 
274a2284e795: Pull complete 
af4655af427d: Pull complete 
2c4d80c984fa: Pull complete 
e8ccdada35ea: Pull complete 
eacf102f2deb: Pull complete 
72724bec4b90: Pull complete 
Digest: sha256:c69438a150200014d50d2203db61450763d3daba0c48f8d8114d909e81b3533e
Status: Downloaded newer image for linuxserver/jackett:latest
```
```[root@VM j0nnymoe]# uname -a
Linux VM 4.16.13-2-ARCH #1 SMP PREEMPT Fri Jun 1 18:46:11 UTC 2018 x86_64 GNU/Linux
root@VM j0nnymoe]# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 18.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.16.13-2-ARCH
Operating System: Antergos Linux
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.856GiB
Name: VM
ID: UMAX:LAHS:D7BY:BIGC:TLWM:WUVS:3BSS:SKQU:5ADS:JZI2:FXOQ:VFD6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

So no idea why that's not working - I'll merge @sparklyballs's PR and hopefully that will fix the issue.

**Comment by arnishow** [comment]
Unfortunately sparklyballs's idea didn't fix it - version 186.

@j0nnymoe What about with userns activated?

**Comment by j0nnymoe** [comment]
Unfortunately I have no idea what userns is...

**Comment by arnishow** [comment]
Sorry, userns = user namespace
It provides isolation for containers.

Please add the following to your daemon.json and let me know:

{
    "userns-remap": "default",
}

**Comment by j0nnymoe** [comment]
To play devils advocate, is there any advantage doing this over just using our PGID/PUID system?

**Comment by arnishow** [comment]
This is a good point.
All images are not as well coded as yours.

**Comment by arnishow** [comment]
Interresting difference between v90 and actual:
v90:
`dr-xr-xr-x 197 root root    0 Jun 13 16:00 proc`
`dr-xr-xr-x  13 root root    0 Jun 13 14:53 sys`

Actual:
`dr-xr-xr-x 326 nobody nogroup    0 Jun 12 23:28 proc`
`dr-xr-xr-x  13 nobody nogroup    0 Jun 13 17:58 sys`

Others images from your team look to run with nobody:nogroup.
