### ISSUE TITLE
How to set this up on Windows

### ISSUE THREAD

**Issue by CiniqueL** [linuxserver/docker-jackett#43]
Can anyone give a layman's explanation for how to set this up on Windows? I keep seeing Linux explanations all over the web (for the past couple of hours)

I'd like to set up Jackett, change the save and log directory - and open the Web UI.

I used [this guide](https://www.htpcbeginner.com/install-jackett-using-docker/) and backtracked once, and I couldn't figure out how to set custom Windows locations, and I'm not able to access the UI.

I used the docker ps command to output this info:

`
PS C:\WINDOWS\system32> docker ps
CONTAINER ID        IMAGE                 COMMAND             CREATED             STATUS              PORTS                                NAMES
9f34df13993d        linuxserver/jackett   "/init"             25 minutes ago      Up 25 minutes       9117/tcp, 0.0.0.0:50169->50169/tcp   jackett`

**Comment by tobbenb** [comment]
None of us use docker on windows, so we can't help I'm afraid.

**Comment by sparklyballs** [comment]
docker on windows is a hit and miss affair tbh and not something we have much if any experience with as we're mostly linux users
