### ISSUE TITLE
add --NoUpdates command line flag

### ISSUE THREAD

**Issue by kaso17** [linuxserver/docker-jackett#44]
Starting with version v0.8.676 jackett has a new command line option `--NoUpdates` which will prevent any kind of self updates. I suggest you add it to the docker init options to prevent the 100% CPU bug (See #34).

**Comment by sparklyballs** [comment]
@kaso17 thanks for the heads up and i've put in a PR #45

**Comment by elliotvr** [comment]
hi @kaso17 and @sparklyballs since this update, Jackett can't be updated easily.
You need to rebuild the container each time you want to update to the last version, no just a restart 😞 .

**Comment by j0nnymoe** [comment]
@elliotvr This is no different to all our other containers.

**Comment by elliotvr** [comment]
@j0nnymoe yes, but Sonarr & Radarr can self-update.
Here, you can no longer update Jackett !
Sonarr & Radarr get updated every month
Jackett get updated every two days (for trackers...), so rebuild your container every two days to access your tracker is not cool !

**Comment by sparklyballs** [comment]
updating an app in a running container is recipe for breakage

this line was put in because the update checker was consuming 100% of system resources on host OS for a very large number of our users

**Comment by j0nnymoe** [comment]
Use docker-compose or something similar to manage your containers for easy rebuilding/updating.

**Comment by elliotvr** [comment]
I'm on Synology NAS, so i'm using Synology Docker interface.
I will try docker-compose.
Thx !

**Comment by FlorianFranconi** [comment]
Hi, I have the same problem on my Synology docker. Impossible to make updates on jackett I have the error:"Info Updates are disabled via --NoUpdates.". I uninstalled and reinstalled the container docker and I still have the same error. If someone has found a solution...

**Comment by sparklyballs** [comment]
updates via the webui have been deliberately disabled

**Comment by FlorianFranconi** [comment]
Ah, it's embarrassing... How do I get the latest version of the coup? Because I have the last docker container available.

**Comment by sparklyballs** [comment]
we build a new version weekly on friday evenings around 11pm uk time

**Comment by elliotvr** [comment]
I'm now using docker-compose to configure my containers now, ssh & root.
```
version: '2'
services:
    jackett:
        # image: linuxserver/jackett:latest
        build: https://github.com/linuxserver/docker-jackett.git
        container_name: jackett
        restart: always
        ports:
            - 9117:9117
        environment:
            - TZ=Europe/Paris
            - PGID=1001
            - PUID=1001
        volumes:
            - /volume1/docker/Jackett:/config```
and use build instead of image.

**Comment by FlorianFranconi** [comment]
Thank you for your feedback, so I'll wait for the update tonight.
If it doesn't work, I will test the solution of @elliotvr.
To use docker-component I need to create a file docker-component. yml at the root of my synology? I am not experienced with Docker, I discover using the Synology interface.

**Comment by sparklyballs** [comment]
@kaso17 

i've setup a ping to our jenkins server if you're interested 

contact us here and i can send you a DM https://discord.gg/YWrKVTn

**Comment by FlorianFranconi** [comment]
Hello, I still have the problem of updates even with the latest version of tonight :(

**Comment by sparklyballs** [comment]
updates via the webui have been disabled

**Comment by FlorianFranconi** [comment]
Oh, all right! Why this choice? So how can we update jackett easily?

**Comment by sparklyballs** [comment]
read ^^^^

**Comment by FlorianFranconi** [comment]
Sorry, I don't understand. So to update Jackett you have to update the container with the version you release every Friday?

**Comment by kaso17** [comment]
The docker container should now be automatically rebuild on every jackett release, so it should be always up to date.

**Comment by sparklyballs** [comment]
yep we and the jackett dev team have worked together to ensure our docker image should always be up to date and you can get the newest version by pulling the image and rebuilding the container

**Comment by aptalca** [comment]
@vinchi007 automatic docker container update has nothing to do with either jackett or linuxserver. We provide a new docker image as soon as a new version of jackett is released. It is your docker manager's responsibility to update the image and recreate the container. There are plenty of solutions for that. Docker compose does it through a `pull` and an `up -d`, rancheros will let you click on an update button, watchtower allows you to set schedules where it automatically updates them, etc.

Our docker images are meant to be static images. They are properly versioned. The containers are ephemeral. The idea is that whoever creates a container on whatever os and environment, should have the same exact experience as long as they use the same image. Auto updating packages inside that image defeats that idea.

**Comment by darkbroodzed** [comment]
@aptalca so now you enforce everyone who use docker image to download full image and rebuild it every time, not just download new files and restart image. 
Great victory over common sense.

**Comment by aptalca** [comment]
@darkbroodzed Not rebuild, but recreate. We build the images and push to the hub. All you would do is update the image (docker pull) and recreate the container

That's how docker containers were meant to be utilized and all of our images have worked that way for a long time.

If you don't like it you're welcome to install jackett yourself and let it update, or build your own docker image. Everything is open source

**Comment by sparklyballs** [comment]
@darkbroodzed common sense is subjective at best 

is it common sense to have a container that updates itself and then breaks because update x needs a dependency that isn't in the container ? 

is it common sense that we have a multitude of people with the same base container version but totally different versions of the app and we have support nightmare scenario ? 

containers as @aptalca said already, are meant to be ephemeral

**Comment by Ansem93** [comment]
Is this bug resolved? Can I remove the --noupdate flag now?
