### ISSUE TITLE
jenkins webhook integration broken

### ISSUE THREAD

**Issue by kaso17** [linuxserver/docker-jackett#47]
Hi,

the webhook to h**ps://ci.linuxserver.io/generic-webhook-trigger/invoke which should trigger new jenkins job runs when a new jackett release is released is failing with the following response:
```json
{"status":"ok","data":{"triggerResults":{"ANY":"Did not find any jobs to trigger! The user invoking /generic-webhook-trigger/invoke must have read permission to any jobs that should be triggered. You may try adding http://user:passw@url... or configuring and passing an authentication token like ...trigger/invoke?token=TOKENHERE"}}}
```

**Comment by phendryx** [comment]
@kaso17 can you ping me (@phendryx) on lsio discord?

**Comment by phendryx** [comment]
Incorrect token was being submitted to webhook.
