### ISSUE TITLE
Jackett don't start on v0.9.6, need Mono 5.8 or greater

### ISSUE THREAD

**Issue by srod** [linuxserver/docker-jackett#52]
Since the release of Jackett v0.9.6, Mono 5.8 or greater is now required.

Please check:  https://github.com/Jackett/Jackett/releases/tag/v0.9.6
`Mono 5.8 or greater is now required to start Jackett`

Thanks !

**Comment by sparklyballs** [comment]
duplicate #51 

exactly why you update the image and not the app
