### ISSUE TITLE
Mono Error when start jackett  since update  0.9.6.0

### ISSUE THREAD

**Issue by kestouf** [linuxserver/docker-jackett#53]
Hello
Since the last update to jackett (0.9.6.0), it does not start anymore and I have this error message:

07-23 00:13:40 Info Starting Jackett 0.9.6.0                                                                      
07-23 00:13:40 Info Environment version: 4.0.30319.42000 (/usr/lib/mono/4.5)                                      
07-23 00:13:40 Info OS version: Unix 3.10.105.0 (64bit OS) (64bit process)                                        
07-23 00:13:40 Info ThreadPool MaxThreads: 400 workerThreads, 200 completionPortThreads                           
07-23 00:13:40 Info App config/log directory: /config/Jackett                                                     
07-23 00:13:40 Info issue: Ubuntu 16.04.3 LTS \n \l                                                               
07-23 00:13:40 Info mono version: 5.4.0.201 (tarball Fri Oct 13 21:51:45 UTC 2017)                                
07-23 00:13:40 Error A minimum Mono version of 5.8 is required. Please update to the latest version from http://www.mono-project.com/download/

But I have the 5.12 version of mono:

root @ mono1: / # cert-sync
Mono Certificate Store Sync - version 5.12.0.226
Populate Mono certificate store from a concatenated list of certificates.
Copyright 2002, 2003 Motus Technologies. Copyright 2004-2008 Novell. BSD licensed.
                                                                                                                  
Usage: cert-sync [--quiet] [--user] system-ca-bundle.crt
Where system-ca-bundle.crt is in PEM format

Thx for your help
Thierry

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

 Synology DS6.2

07-23 00:13:40 Info Starting Jackett 0.9.6.0                                                                      
07-23 00:13:40 Info Environment version: 4.0.30319.42000 (/usr/lib/mono/4.5)                                      
07-23 00:13:40 Info OS version: Unix 3.10.105.0 (64bit OS) (64bit process)                                        
07-23 00:13:40 Info ThreadPool MaxThreads: 400 workerThreads, 200 completionPortThreads                           
07-23 00:13:40 Info App config/log directory: /config/Jackett                                                     
07-23 00:13:40 Info issue: Ubuntu 16.04.3 LTS \n \l                                                               
07-23 00:13:40 Info mono version: 5.4.0.201 (tarball Fri Oct 13 21:51:45 UTC 2017)                                
07-23 00:13:40 Error A minimum Mono version of 5.8 is required. Please update to the latest version from http://www.mono-project.com/download/

**Comment by tobbenb** [comment]
Update the image and not the app inside the container.
You are checking the mono version on your Nas and not inside the container.
