### ISSUE TITLE
Automatic builds on every release using outdated tag

### ISSUE THREAD

**Issue by h45rd** [linuxserver/docker-jackett#54]
Thanks for this docker.

Due to github API's handling of pre-releases [this line](https://github.com/linuxserver/docker-jackett/blob/master/Dockerfile#L22) in your dockerfile pulls the wrong tag if it is marked as pre-release.

Would probably be better to use https://api.github.com/repos/Jackett/Jackett/tags for pulling tags.
If you do not want to use pre-releases for the main tag, could you alternatively provide a dev tag for the bleeding edge and limit automatic builds of the main tag to new releases?

Right now every tagged (pre-)release in the Jackett repo triggers a build of the main tag, using the same outdated v0.9.41, as v0.10.x releases are tagged as pre-releases.

**Comment by sparklyballs** [comment]
we get a ping from jackett everytime they make a release, be it pre-release or otherwise. 

our jenkins builds the image on that ping.

we currently have no plans to use pre-release versions

0.9.4.1 is not "outdated" by any stretch of the imagination, it is the latest release.

**Comment by h45rd** [comment]
Wow.. you are fast :)
Understood.

Didn't mean to criticize or trivialize your work.
Just didn't realize building on every release, even when it is not used due to being a pre-release, would be intentional.
Might be a while to the next "full" release due to the switch to kestrel, though.

Best,
h45rd

**Comment by d1slact0r** [comment]
there is a new latest release but nothing got update (8 days ago)

**Comment by sparklyballs** [comment]
@d1slact0r 

![screen shot 2018-09-14 at 09 52 21](https://user-images.githubusercontent.com/4343808/45540297-f3d47580-b803-11e8-9dcc-d3a06e5d7921.png)
 
github release

![screen shot 2018-09-14 at 09 52 28](https://user-images.githubusercontent.com/4343808/45540320-0353be80-b804-11e8-9f58-b7b53a1f4300.png)


screen shot of my jackett container showing the version.

as you can see it is up to date. i suggest you update your image.

**Comment by d1slact0r** [comment]
sorry my watchtower crashed restart and all is updated ;)
