### ISSUE TITLE
Jackett container freezes every 6-10 hours 

### ISSUE THREAD

**Issue by cybercar** [linuxserver/docker-jackett#55]
Docker version: 18.06.1-ce
Jackett version: v0.10.97.0
Mono version: 5.14.0.177

Hi,
Every 5-8 hours my sonarr and radarr tells me that the jackett indexrs couldnt be found, I check and cannot access to webui jacket server.

If I enter the container it seams running.
I read the logs and cant find anything that points me in the good direction.

I have auto-update disabled.

The freezes are just random.
I have docker installed on Openmediavault.

Here i post the logs.

Hope you can help me.

Thanks

Jackett log:

[log.txt](https://github.com/linuxserver/docker-jackett/files/2325713/log.txt)

Alse sonarr log if it helps

[sonarr.txt](https://github.com/linuxserver/docker-jackett/files/2325716/sonarr.txt)

**Comment by sparklyballs** [comment]
i think this is probably best asked at the jackett git repository 

https://github.com/Jackett/Jackett

they would be better placed to examine the log and tell whether it is specifically an issue with the app or the docker image.
