### ISSUE TITLE
Jackett starts okay, runs for a while, crashes. Recreating does not fix.

### ISSUE THREAD

**Issue by pww217** [linuxserver/docker-jackett#57]
I run it in a container on an Ubuntu system along with related apps, none of which have issues. I have seen a similar bug here and the suggestion is to repull/update the image, but that hasn't worked for more than a couple hours at a time, if even.

 Host OS:  Ubuntu 18.04

Command line users, your run/create command, GUI/Unraid users, a screenshot of your template settings.

docker create \
--name=jackett \
-v /home/[redacted]/.config/Jackett:/config \
-v /tmp/torrents/:/downloads \
-e PGID=1000 -e PUID=1000 \
-e TZ="Los Angeles" \
-v /etc/localtime:/etc/localtime:ro \
-p 9117:9117 \
	--restart unless-stopped \
linuxserver/jackett

Docker log output, docker log <container-name>

Repeated exceptions.

[dockerlog.txt](https://github.com/linuxserver/docker-jackett/files/2412233/dockerlog.txt)

Mention if you're using symlinks on any of the volume mounts.

Don't believe so. Should all be direct. Device it's writing to is external USB drive mounted under /media.

##  Thanks, team linuxserver.io

The log file attached is the same whether the Jackett or Docker log file.

**Comment by nfugal** [comment]
I'm having a similar issue on a new installation.

**Comment by j0nnymoe** [comment]
Please report the error directly to jackett, they will be able to tell if it's a container issue or something wrong with jackett itself.

**Comment by pww217** [comment]
Alrightly thank you.

**Comment by sparklyballs** [comment]
@Tekka90 i'm not convinced that particular issue is relevant 

if it were , then every user of the jackett container would be experiencing the same issue, which is far from the truth.

**Comment by sparklyballs** [comment]
need the output of the following two commands run on the host..

```
docker inspect -f '{{ index .Config.Labels "build_version" }}' linuxserver/jackett
docker inspect -f '{{ index .Config.Labels "build_version" }}' jackett
```

the first one the container name may need changing, the second should be run verbatim.

**Comment by j0nnymoe** [comment]
Yes make sure your TZ is correctly setup. Also you might want to pull a more updated image since yours is using a build from January.
