### ISSUE TITLE
Image size is 500 mb

### ISSUE THREAD

**Issue by aaomidi** [linuxserver/docker-jackett#58]
Does this image really need to be this big? Can we use alpine or something else lightweight instead?

**Comment by thelamer** [comment]
I assure you, we only use Ubuntu when we absolutely have to. 
When it comes to mono applications the methodology for adding mono is to use an unsupported glibc package as Alpine does not natively support Glibc. Using this method while conventionally functional results in a mountain of support requests revolving around oddities that happen when using slightly different mono versions and build environments from the development team. 

If you identify any specific areas where this image can be made leaner please open a pull request or new issue.
