### ISSUE TITLE
every day a new "release" is generated

### ISSUE THREAD

**Issue by neothematrix** [linuxserver/docker-jackett#59]
Hi,
I noticed that for some reason, there is a new "jackett" release created every day, apparently, with no commit in the middle, you can see that here: https://github.com/linuxserver/docker-jackett/releases you'll notice that the referenced commit (66f991e) is always the same since June.
This also leads to a new docker image created on the docker hub: https://hub.docker.com/r/linuxserver/jackett/tags/
is this a wanted behaviour?

thanks

**Comment by sparklyballs** [comment]
yes.

whenever jackett releases a new version, their build server pings our to create a new image.
