### ISSUE TITLE
Update to last

### ISSUE THREAD

**Issue by moarf56** [linuxserver/docker-jackett#60]
Hi I use this image to run Jackett, and I can find a way to update to the last jackette releases.

I use Debian 9 and I run Jackett Version 0.10.455.0 but v0.10.467 is up.

Thk

**Comment by homerr** [comment]
It'll be updated on Saturday's build. It would have been already, but DockerHub had problems over the weekend.

**Comment by j0nnymoe** [comment]
You will also need to make sure you pull the latest images and rebuild the container to get the update.

**Comment by moarf56** [comment]
Okay thx you :d
