### ISSUE TITLE
Rasberry PI docker "exec format error"

### ISSUE THREAD

**Issue by d1slact0r** [linuxserver/docker-jackett#61]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	
I am running HASSIO on my Rasberry Pi3B+ and with portainer for docker. When I launch jackett I get:
```
standard_init_linux.go:190: exec user process caused "exec format error"
```
What could be the culprit ?

**Comment by j0nnymoe** [comment]
Need to use https://hub.docker.com/r/lsioarmhf/jackett/ as this build is specifically for arm devices.
