### ISSUE TITLE
Not starting up on a raspberry pi 

### ISSUE THREAD

**Issue by HUFGhani** [linuxserver/docker-jackett#64]
I'm running this in a docker container on a raspberry pi 3 getting the following error in the logs when ever I start it up 
 
standard_init_linux.go:190: exec user process caused "exec format error",
standard_init_linux.go:190: exec user process caused "exec format error",
standard_init_linux.go:190: exec user process caused "exec format error",
standard_init_linux.go:190: exec user process caused "exec format error",
standard_init_linux.go:190: exec user process caused "exec format error",
standard_init_linux.go:190: exec user process caused "exec format error",

the configuratoin is the follwoing 

docker create --name=jackett \
--restart=always \
-v /home/docker/jackett/config:/config \
-v /home/docker/jackett/downloads:/downloads \
-e PGID=1000 -e PUID=1000 \
-e TZ=/etc/localtime:/etc/localtime:ro  \
-p 82:9117 \
linuxserver/jackett

the image 
Linuxserver.io version:- 357 Build-date:- December-18-2018-19:13:59-UTC

**Comment by j0nnymoe** [comment]
You're running the image for x64, you need the lsioarmhf/jackett image.
