### ISSUE TITLE
High CPU usage when using Sock5 Proxy

### ISSUE THREAD

**Issue by tradenet** [linuxserver/docker-jackett#70]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by tradenet** [comment]
Version 0.10.724.0
and docker version 18.09.1
Similar to:  https://github.com/Jackett/Jackett/issues/2602
Removing proxy Sock5 causes the issue to go away.

**Comment by thelamer** [comment]
This does not seem to have anything to do with us putting this app in a docker container given the thread you linked. 
Please understand that while we do try to help where we can this is an application specific issue and not something we can troubleshoot with our codebase consisting of docker build logic.
