### ISSUE TITLE
Unable to create custom definitions

### ISSUE THREAD

**Issue by jeremybell** [linuxserver/docker-jackett#72]
I'd like to create a custom definition for a site not supplied, but the /definitions/ folder is held within the container itself. Is it possible to map /definitions/ to a virtual folder so new sites can be added?

**Comment by aptalca** [comment]
I looked into it and it seems it would be rare for users to want to create their own definitions for personal use. It's best to PR definitions upstream so they are added to Jackett.

However, you can map your definition into that folder via `-v /path/to/your/definition:/app/Jackett/Definitions/blah.yml`

**Comment by flightlevel** [comment]
You can already do this today
Jackett checks 3 folders for definitions (they get logged when you startup)
2019-02-20 22:14:38.8480 Info Loading Cardigann definitions from: `/config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Jackett/Definitions` 
i.e. put them in `/config/cardigann/definitions/`, you'd already have the config folder mapped

**Comment by aptalca** [comment]
Oh well, that's great to know.

**Comment by GautierT** [comment]
Hi !
I created folders `cardigann/definitions/` in config/ and added a new definition in it but when i restart the docker container this definition doesn't seems to be picked off by Jacket... 
What i am doing wrong ? Thanks.
