### ISSUE TITLE
huge size of virtual memory

### ISSUE THREAD

**Issue by karkaaa** [linuxserver/docker-jackett#78]
Hello,

It is docker image problem or jackett? How to fix it?

VIRT 20GB

![image](https://user-images.githubusercontent.com/34538939/54347770-5641ed80-4650-11e9-8394-9699f4c86b77.png)

```
root@:~# docker -v
Docker version 18.09.3
```

Image info:
`Linuxserver.io version:- v0.11.36-ls14 Build-date:- 2019-03-13T08:07:09+00:00`

```
docker create \
--name=jackett \
--restart=always \
--restart unless-stopped \
-e PGID=1000 -e PUID=1000 \
-e TZ=Europe/London \
-v /home/docker/jackett/config:/config \
-v /mnt/media:/downloads \
-p 9117:9117 \
linuxserver/jackett
```

**Comment by sparklyballs** [comment]
there is no problem or issue, VIRT is a bit more complicated than saying jackett is actually using that amount of memory.

https://stackoverflow.com/questions/23187228/what-is-virt-column-in-htop-memory-overhead

the RES column is what you should be looking at.

**Comment by flightlevel** [comment]
Yep and explained here by Microsoft https://tinyurl.com/y2asz7oo as well
