### ISSUE TITLE
Not starting up on raspberry pi

### ISSUE THREAD

**Issue by romadiz** [linuxserver/docker-jackett#83]
Hi,

I'm running radarr, sonarr and jackett in a raspberry pi using docker compose.

```
jackett: 
  container_name: jackett 
  restart: unless-stopped 
  ports: 
   - 9117:9117 
  volumes: 
   - /home/dockeras/jackett:/config 
  environment: 
   - PUID=1000 
   - PGID=150 
   - TZ=Europe/Madrid 
  image: linuxserver/jackett
```
When I start the apps (docker-compose up -d) Sonarr and Radarr starts fine but not Jackett. I have this error
```
FailFast:
Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.

   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at System.AppDomain.InitializeCompatibilityFlags()
   at System.AppDomain.CreateAppDomainManager()
   at System.AppDomain.Setup(System.Object)
```

I've just update the images.

**Comment by flightlevel** [comment]
https://github.com/dotnet/corefx/blob/master/Documentation/architecture/globalization-invariant-mode.md

If you add an extra environment variable `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1` does it then work?
Do you only use english language trackers and what is your host OS?

**Comment by romadiz** [comment]
I don´t know what happened but after I format jackett is working fine again. Thanks.

**Comment by romadiz** [comment]
I don´t know what happened but after I format jackett is working fine again. Thanks.

**Comment by romadiz** [comment]
I had a new error now when jacket try to start up. 

I have this docker compose

`jackett:
                container_name: jackett
                restart: unless-stopped
                ports:
                        - 9117:9117
                volumes:
                        - /home/pi/jackett:/config
                        - /home/pi/media/disco/downloads/completed/complete:/downloads
                environment:
                        - PUID=1000
                        - PGID=150
                        - TZ=Europe/Madrid
                        - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
                image: linuxserver/jackett`

But when I tried to start up I get this error

`error while loading shared libraries: libpthread.so.0: cannot open shared object file: No such file or directory`

I don't know if I have to add some library. I'm using raspbian fetch in a Raspberry Pi 3.

Thanks!!

**Comment by sparklyballs** [comment]
Don't reopen closed issues.. 

For a new problem, file a new issue.
