### ISSUE TITLE
HTTP 400 Error on every post from the UI

### ISSUE THREAD

**Issue by JRascagneres** [linuxserver/docker-jackett#84]
I appear to be getting HTTP 400 Errors when issuing POST requests from the UI. I've had a look around and seem to be hitting the issue described in a previous issue here: https://github.com/linuxserver/docker-jackett/issues/63#issuecomment-460004550

I don't understand the solution that was provided there. Can anyone help?

**Comment by thelamer** [comment]
they are specifically talking about modifying their reverse proxy setups specifically https://github.com/dperson/nginx/blob/master/nginx.sh#L460-L461 in Nginx. 
Does this apply to you?

**Comment by JRascagneres** [comment]
@thelamer Yes I am using that proxy as part of jackett running through an openvpn client container.

**Comment by thelamer** [comment]
Ok so this is a third party proxy to our container that needs to be modified. For support requests please try our discord: (specifically #other-support)
https://discord.gg/YWrKVTn
Github really is for bug reports and feature requests.
