### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by karkaaa** [linuxserver/docker-jackett#87]
Hello,

```
Build version | Linuxserver.io version:- v0.11.440-ls27 Build-date:- 2019-06-22T21:11:49+00:00
OS Information | linux x86_64 Ubuntu 18.04.2 LTS
Kernel Version | 4.18.0-24-generic
Docker version | 18.09.6, build 481bc77
```

Not working https://torrent.ai

Error:
![image](https://user-images.githubusercontent.com/34538939/60206482-53b08000-985c-11e9-9434-4005d3fcc2e7.png)

Maybe need this on container:
https://github.com/Jackett/Jackett/issues/2111

Thx.

**Comment by thelamer** [comment]
This container uses Ubuntu CA chain which includes lets encrypt <https://github.com/linuxserver/docker-jackett/blob/master/package_versions.txt#L9>
Please report this upstream if you are still running into this, we will not be manually ingesting ca certs from http endpoints.
