### ISSUE TITLE
lsioarmhf/jackett:latest Working on WD mycloud ex2 ultra but not linuxserver/docker-jackett

### ISSUE THREAD

**Issue by Brysky** [linuxserver/docker-jackett#90]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	
Hi, i don't have any information on this because i'm not expert in docker but the deprecated version on lsioarmhf/jackett:latest does work on my docker (v18) on my cloud EX2 ultra but all the versions from linuxserver (armv7 / v8 and amd4, no one is working but there is no log, it just blocks with those last logs : 

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-config: executing... 
[services.d] starting services
[services.d] done.
and then there's nothing more. On Isio it goes forward an launch Jackett.

 WD my cloud Ultra EX2
 Using docker create recommended without IDs and timezone. Everything is untouched

**Comment by CHBMB** [comment]
I don't know what CPU the hardware you have is using, but I'm suspicious it might be ARMv6 which we dropped support for.

**Comment by Brysky** [comment]
> I don't know what CPU the hardware you have is using, but I'm suspicious it might be ARMv6 which we dropped support for.

Marvell ARMADA 385 1.3GHz

**Comment by CHBMB** [comment]
Can you post the actual command you're using to run?

**Comment by Brysky** [comment]
docker create \
  --name=jackett \
  -p 9117:9117 \
  -v /mnt/HD/HD_a2/Nas_Prog/_docker/volumes/jackett_config:/config \
  -v /mnt/HD/HD_a2/Nas_Prog/_docker/volumes/jackett_blackhole:/downloads \
  --restart unless-stopped \
  linuxserver/jackett

and the logs are stopping there : 
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-config: executing...
[services.d] starting services
**[services.d] done.**

**Comment by CHBMB** [comment]
Can you post the full logs

**Comment by Brysky** [comment]
> Can you post the full logs

Those are the full logs, there is nothing after that ^^'

**Comment by CHBMB** [comment]
They're not the full logs, they're stuff before that too.

```
| | ___ _ __
| | / __| | | / \
| | \__ \ | | | () |
|_| |___/ |_| \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid: 99
User gid: 100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by Brysky** [comment]
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.


[s6-init] ensuring user provided files have correct perms...exited 0.


[fix-attrs.d] applying ownership & permissions fixes...


[fix-attrs.d] done.


[cont-init.d] executing container initialization scripts...


[cont-init.d] 10-adduser: executing... 


usermod: no changes




-------------------------------------


          _         ()


         | |  ___   _    __


         | | / __| | |  /  \ 


         | | \__ \ | | | () |


         |_| |___/ |_|  \__/






Brought to you by linuxserver.io


We gratefully accept donations at:


https://www.linuxserver.io/donate/


-------------------------------------


GID/UID


-------------------------------------




User uid:    911


User gid:    911


-------------------------------------




[cont-init.d] 10-adduser: exited 0.


[cont-init.d] 30-config: executing... 


[cont-init.d] 30-config: exited 0.


[cont-init.d] 99-custom-scripts: executing... 


[custom-init] no custom files found exiting...


[cont-init.d] 99-custom-scripts: exited 0.


[cont-init.d] done.


[services.d] starting services


[services.d] done.

**Comment by CHBMB** [comment]
Have you tried setting the PUID and GUID?  

My feeling is this is a CPU architecture issue as discussed [here](https://github.com/linuxserver/docker-ombi/issues/48) but until you are running the container as intended, I can't really troubleshoot any further.

**Comment by CHBMB** [comment]
The command `docker version` may yield a useful result.

**Comment by CHBMB** [comment]
Yep, pretty sure it's a CPU issue, or more specifically the Western Digital firmware uses armel, despite the CPU being hf compatible.

https://github.com/MediaBrowser/Emby/issues/3298#issuecomment-393056945 discussed it here.

Sorry, I think your out of luck, IIRC Alpine Linux has dropped support for that version of ARM as well so even if we wanted to, we could only offer images based on an old version of Alpine which no longer gets updates/security patches.

**Comment by Brysky** [comment]
Thanks for trying ! 

anyways i will receive soon an Intel Nuc8i3 as a 4K media player, it should also be able to host Jackett/Sonarr/Radarr/Transmission without problems I think. I will leave the WD as a storage unit. 

Have a nice day.
