### ISSUE TITLE
Problem with french tracker YggTorrent

### ISSUE THREAD

**Issue by MrMinet** [linuxserver/docker-jackett#91]
Hello Guys,
I'm using docker-jakett since few weeks now (https://github.com/MrMinet/Plex-DC-stack), and I have a problem since 2 or 3 days.

To be as short as possible, here is the official issue and how to solve it : 

https://github.com/Jackett/Jackett/issues/6341 

It seems that the last Jackett version 0.12.990.0 is not included in linuxserver/docker-jackett.

**Comment by aptalca** [comment]
It was released within an hour of the upstream release: https://github.com/linuxserver/docker-jackett/releases/tag/v0.12.990-ls45

**Comment by ThomasJacqueminet** [comment]
Thanks a lot !
