### ISSUE TITLE
Old version?

### ISSUE THREAD

**Issue by ageisen2000** [linuxserver/docker-jackett#92]
Jackett version is very old
------------------------------

## Expected Behavior
Container should be updated to the newest release version of jackett

## Current Behavior
Container seems to not be updated

Message at the bottom of the screen:
`Your version of Jackett v0.11.481.0 is very old. Multiple indexers are likely to fail when using an old version. Update to the latest version of Jackett.`

## Steps to Reproduce
pull the container and run. You'll get a message at the bottom saying jackett is out of date

## Environment
**OS:**      Ubuntu
**CPU architecture:** x86_64
**How docker service was installed:**      
Using the steps from the website

**Comment by aptalca** [comment]
The version of the latest tag is `v0.12.1024`

Pull the hardest image and recreate the container
