### ISSUE TITLE
chown on startup.

### ISSUE THREAD

**Issue by jacksonwilliams** [linuxserver/docker-jackett#93]
there is  
```
echo "**** fix for host id mapping error ****" && \
 chown -R root:root /app/Jackett && \
```
in the docker file.

why is executing 30-config required? as it is just doing a chown again?
```
chown -R abc:abc \
	/app \
	/config \
	/downloads
```

doing a chown over the entire contence of a downloads folder dramatically increases the start up time.
if this is just for being able to download torrent files into the folder, then it should not require the '-R' recursive flag

**Comment by homerr** [comment]
Hi, fixed with #95 and #94 

Cheers
