### ISSUE TITLE
The latest update caused an error in both sonarr and radarr

### ISSUE THREAD

**Issue by mdschulte** [linuxserver/docker-jackett#99]
After the current update to the container I began seeing this error when sonarr or radarr tried to connect to Jackett:

System.ArgumentNullException: Value cannot be null. (Parameter 'second')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Intersect[TSource](IEnumerable1 first, IEnumerable1 second)
   at Jackett.Common.Indexers.BaseIndexer.<>cDisplayClass65_0.<FilterResults>b0(ReleaseInfo result) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 268
   at System.Linq.Enumerable.WhereListIterator1.MoveNext()
   at System.Linq.Enumerable.EnumerablePartition1.MoveNext()
   at System.Linq.Enumerable.SelectIPartitionIterator2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator2.MoveNext()
   at System.Linq.Set1.UnionWith(IEnumerable1 other)
   at System.Linq.Enumerable.DistinctIterator1.FillSet()
   at System.Linq.Enumerable.DistinctIterator1.ToArray()
   at System.Linq.Buffer1..ctor(IEnumerable1 source)
   at System.Linq.OrderedEnumerable1.GetEnumerator(Int32 minIdx, Int32 maxIdx)+MoveNext()
   at System.Linq.Enumerable.SelectIPartitionIterator2.LazyToArray()
   at System.Linq.Enumerable.SelectIPartitionIterator2.ToArray()
   at System.Linq.Buffer1..ctor(IEnumerable1 source)
   at System.Linq.OrderedEnumerable1.GetEnumerator()+MoveNext()
   at Jackett.Common.Services.CacheService.CacheRssResults(IIndexer indexer, IEnumerable1 releases) in /home/vsts/work/1/s/src/Jackett.Common/Services/CacheService.cs:line 31
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 383

I deleted the image and did a re-pull and it still persisted.

I then reverted back to v0.13.201-ls55 and the issue goes away.

Host OS is Ubuntu 18.04, x86_64
Installed via dockstarter: bash -c "$(curl -fsSL https://get.dockstarter.com)"

## Command used to create docker container (run/create/compose/screenshot)
Here is the current state of the container:
{
    "AppArmorProfile": "docker-default",
    "Args": [],
    "Config": {
        "AttachStderr": false,
        "AttachStdin": false,
        "AttachStdout": false,
        "Cmd": null,
        "Domainname": "",
        "Entrypoint": [
            "/init"
        ],
        "Env": [
            "PGID=1000",
            "PUID=1000",
            "TZ=America/Chicago",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "HOME=/root",
            "LANGUAGE=en_US.UTF-8",
            "LANG=en_US.UTF-8",
            "TERM=xterm",
            "XDG_DATA_HOME=/config",
            "XDG_CONFIG_HOME=/config"
        ],
        "ExposedPorts": {
            "9117/tcp": {}
        },
        "Hostname": "DockSTARTer",
        "Image": "linuxserver/jackett:v0.13.201-ls55",
        "Labels": {
            "build_version": "Linuxserver.io version:- v0.13.201-ls55 Build-date:- 2020-02-25T11:54:23+00:00",
            "com.docker.compose.config-hash": "a468580d6a5c0c3526a9488ee108c67ce94935cf4388dcb25b3a9a845e74c7df",
            "com.docker.compose.container-number": "1",
            "com.docker.compose.oneoff": "False",
            "com.docker.compose.project": "compose",
            "com.docker.compose.project.config_files": "docker-compose.yml,docker-compose.override.yml",
            "com.docker.compose.project.working_dir": "/home/gimpy/.docker/compose",
            "com.docker.compose.service": "jackett",
            "com.docker.compose.version": "1.25.0",
            "maintainer": "thelamer"
        },
        "OnBuild": null,
        "OpenStdin": false,
        "StdinOnce": false,
        "Tty": false,
        "User": "",
        "Volumes": {
            "/config": {},
            "/data": {},
            "/downloads": {},
            "/etc/localtime": {},
            "/shared": {}
        },
        "WorkingDir": ""
    },
    "Created": "2020-02-26T17:00:52.729472044Z",
    "Driver": "overlay2",
    "ExecIDs": null,
    "GraphDriver": {
        "Data": {
            "LowerDir": "/var/lib/docker/overlay2/ca824e1ba17de8f2c5c8534a48e1c22a5423974870cd353816bc7f4bbeed9dac-init/diff:/var/lib/docker/overlay2/55e655fd9bfe9a26d863bc27ee0dd9ff57cfdad8a254b03631fc0c2a152e2e43/diff:/var/lib/docker/overlay2/a43ed2478fe8e3c11e662e74138b2399c1f6e48dfdde63c30922b2db0e7eefe1/diff:/var/lib/docker/overlay2/27b81b72b41641687bd26dd21ab47f3aea118b7aa5e0641afaaf4e52041d87e2/diff:/var/lib/docker/overlay2/36456bea8eb339c7f4a26e11f9cf06461f5ed3f6f7947be786bb025d5693e099/diff:/var/lib/docker/overlay2/ff6c66a025ce3e72baa1a2a3ef4c59c7a1cb368e3d29834f36ffd97960a8fc85/diff:/var/lib/docker/overlay2/32e26a4ce7daba4b8422d0b9366b52eaf84e44be534f986cc425f9521e276c83/diff",
            "MergedDir": "/var/lib/docker/overlay2/ca824e1ba17de8f2c5c8534a48e1c22a5423974870cd353816bc7f4bbeed9dac/merged",
            "UpperDir": "/var/lib/docker/overlay2/ca824e1ba17de8f2c5c8534a48e1c22a5423974870cd353816bc7f4bbeed9dac/diff",
            "WorkDir": "/var/lib/docker/overlay2/ca824e1ba17de8f2c5c8534a48e1c22a5423974870cd353816bc7f4bbeed9dac/work"
        },
        "Name": "overlay2"
    },
    "HostConfig": {
        "AutoRemove": false,
        "Binds": [
            "/home/gimpy/.config/appdata/shared:/shared:rw",
            "/etc/localtime:/etc/localtime:ro",
            "/home/gimpy/.config/appdata/jackett:/config:rw",
            "/mnt/downloads:/downloads:rw",
            "/mnt/downloads:/data:rw"
        ],
        "BlkioDeviceReadBps": null,
        "BlkioDeviceReadIOps": null,
        "BlkioDeviceWriteBps": null,
        "BlkioDeviceWriteIOps": null,
        "BlkioWeight": 0,
        "BlkioWeightDevice": null,
        "CapAdd": null,
        "CapDrop": null,
        "Capabilities": null,
        "Cgroup": "",
        "CgroupParent": "",
        "ConsoleSize": [
            0,
            0
        ],
        "ContainerIDFile": "",
        "CpuCount": 0,
        "CpuPercent": 0,
        "CpuPeriod": 0,
        "CpuQuota": 0,
        "CpuRealtimePeriod": 0,
        "CpuRealtimeRuntime": 0,
        "CpuShares": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "DeviceCgroupRules": null,
        "DeviceRequests": null,
        "Devices": null,
        "Dns": null,
        "DnsOptions": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "GroupAdd": null,
        "IOMaximumBandwidth": 0,
        "IOMaximumIOps": 0,
        "IpcMode": "shareable",
        "Isolation": "",
        "KernelMemory": 0,
        "KernelMemoryTCP": 0,
        "Links": null,
        "LogConfig": {
            "Config": {
                "max-file": "10",
                "max-size": "200k"
            },
            "Type": "json-file"
        },
        "MaskedPaths": [
            "/proc/asound",
            "/proc/acpi",
            "/proc/kcore",
            "/proc/keys",
            "/proc/latency_stats",
            "/proc/timer_list",
            "/proc/timer_stats",
            "/proc/sched_debug",
            "/proc/scsi",
            "/sys/firmware"
        ],
        "Memory": 0,
        "MemoryReservation": 0,
        "MemorySwap": 0,
        "MemorySwappiness": null,
        "NanoCpus": 0,
        "NetworkMode": "compose_default",
        "OomKillDisable": false,
        "OomScoreAdj": 0,
        "PidMode": "",
        "PidsLimit": null,
        "PortBindings": {
            "9117/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "9117"
                }
            ]
        },
        "Privileged": false,
        "PublishAllPorts": false,
        "ReadonlyPaths": [
            "/proc/bus",
            "/proc/fs",
            "/proc/irq",
            "/proc/sys",
            "/proc/sysrq-trigger"
        ],
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": "unless-stopped"
        },
        "Runtime": "runc",
        "SecurityOpt": null,
        "ShmSize": 67108864,
        "UTSMode": "",
        "Ulimits": null,
        "UsernsMode": "",
        "VolumeDriver": "",
        "VolumesFrom": []
    },
    "HostnamePath": "/var/lib/docker/containers/be1bf749803a6f6da9c8efd3203a4dd140acdca0e7dee2afad1772cf3ae9c1d6/hostname",
    "HostsPath": "/var/lib/docker/containers/be1bf749803a6f6da9c8efd3203a4dd140acdca0e7dee2afad1772cf3ae9c1d6/hosts",
    "Id": "be1bf749803a6f6da9c8efd3203a4dd140acdca0e7dee2afad1772cf3ae9c1d6",
    "Image": "sha256:6220b2a79d7983a22408945e5fb21d1cc6d382a86fd1fdd6a31be78ed9d8e1bf",
    "LogPath": "/var/lib/docker/containers/be1bf749803a6f6da9c8efd3203a4dd140acdca0e7dee2afad1772cf3ae9c1d6/be1bf749803a6f6da9c8efd3203a4dd140acdca0e7dee2afad1772cf3ae9c1d6-json.log",
    "MountLabel": "",
    "Mounts": [
        {
            "Destination": "/data",
            "Mode": "rw",
            "Propagation": "rprivate",
            "RW": true,
            "Source": "/mnt/downloads",
            "Type": "bind"
        },
        {
            "Destination": "/shared",
            "Mode": "rw",
            "Propagation": "rprivate",
            "RW": true,
            "Source": "/home/gimpy/.config/appdata/shared",
            "Type": "bind"
        },
        {
            "Destination": "/etc/localtime",
            "Mode": "ro",
            "Propagation": "rprivate",
            "RW": false,
            "Source": "/etc/localtime",
            "Type": "bind"
        },
        {
            "Destination": "/config",
            "Mode": "rw",
            "Propagation": "rprivate",
            "RW": true,
            "Source": "/home/gimpy/.config/appdata/jackett",
            "Type": "bind"
        },
        {
            "Destination": "/downloads",
            "Mode": "rw",
            "Propagation": "rprivate",
            "RW": true,
            "Source": "/mnt/downloads",
            "Type": "bind"
        }
    ],
    "Name": "/jackett",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "",
        "Networks": {
            "compose_default": {
                "Aliases": [
                    "jackett",
                    "be1bf749803a"
                ],
                "DriverOpts": null,
                "EndpointID": "77082d58578cef1edc4ac7583bf2e2ba2ba9b507ec1e1c2fc665cdc1e0d9732f",
                "Gateway": "172.18.0.1",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "IPAMConfig": null,
                "IPAddress": "172.18.0.2",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "Links": null,
                "MacAddress": "02:42:ac:12:00:02",
                "NetworkID": "3a3586594e9bfc01ee011484d84afee3b12947cb5533ecaeffa38fa4cd85740d"
            }
        },
        "Ports": {
            "9117/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "9117"
                }
            ]
        },
        "SandboxID": "3491ab3ed83f30784226a77e006fcc204064d55baa035a1e4fd8ac7e6e128373",
        "SandboxKey": "/var/run/docker/netns/3491ab3ed83f",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "Path": "/init",
    "Platform": "linux",
    "ProcessLabel": "",
    "ResolvConfPath": "/var/lib/docker/containers/be1bf749803a6f6da9c8efd3203a4dd140acdca0e7dee2afad1772cf3ae9c1d6/resolv.conf",
    "RestartCount": 0,
    "State": {
        "Dead": false,
        "Error": "",
        "ExitCode": 0,
        "FinishedAt": "0001-01-01T00:00:00Z",
        "OOMKilled": false,
        "Paused": false,
        "Pid": 25487,
        "Restarting": false,
        "Running": true,
        "StartedAt": "2020-02-26T17:01:03.278665323Z",
        "Status": "running"
    }
}

## Docker logs
To get the logs of the error I would have to go back to the broken build, which I would rather not do but if absolutely necessary I can do it.

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/pull/7338

**Comment by j0nnymoe** [comment]
Pull the latest version of the container and you'll get the update.
